Vlada/atoms cards
sinfin/folio pull request #184
Opened 2023-12-15 11:33 UTC by VladaTrefil

Karty XS - L

2023-12-18 16:06 UTC, mreq requested changes
na prvni otevreni tam vidim spoustu frontendovych nedodelku - prosim, projdi to znovu cele oproti figme a poradne to otestuj, pak na to kouknu znova, diky

2023-12-18 16:06 UTC, mreq commented on test/dummy/app/components/dummy/molecule/cards/extra_small_component.slim
> +                = atom.subtitle
na mobilu namackane 
![image](https://github.com/sinfin/folio/assets/1286942/5cdcbfd7-6862-4c32-890e-83508440d4ce)

2023-12-18 16:06 UTC, mreq commented on test/dummy/app/components/dummy/molecule/cards/extra_small_component.slim
> +                = atom.subtitle
male take 
![image](https://github.com/sinfin/folio/assets/1286942/cb6f73f9-b34a-48d5-a046-cfddf60ad7ac)

2024-01-05 11:07 UTC, VladaTrefil commented on test/dummy/app/components/dummy/molecule/cards/extra_small_component.slim
> +                = atom.subtitle
Opraveno.

2024-01-05 11:08 UTC, VladaTrefil commented on test/dummy/app/components/dummy/molecule/cards/large_component.sass
> +  @media screen and (max-width: 992px) and (min-width: 552px)
Opraveno.

2024-01-08 16:46 UTC, VladaTrefil commented
@mreq Opravil jsem pripominky.

2024-01-09 10:10 UTC, mreq commented on test/dummy/app/components/dummy/molecule/cards/small_component.sass
> +    padding: $grid-gutter-base * 4
na mobilu a tabletu ma byt mensi padding

2024-01-09 10:11 UTC, mreq commented on test/dummy/app/components/dummy/molecule/cards/small_component.sass
> +    gap: $grid-gutter-width
na mobilu ma byt mensi vertikalni gap

2024-01-09 10:14 UTC, mreq commented on test/dummy/app/components/dummy/molecule/cards/medium_component.slim
>          .d-molecule-cards-medium__card
@VladaTrefil nepocitas tady s `url`, ktery atom muze mit; pridal jsem ti do showcase

2024-01-09 10:17 UTC, mreq commented on test/dummy/app/components/dummy/molecule/cards/medium_component.sass
> +    min-height: 200px
nedava smysl bez obrazku

2024-01-09 10:19 UTC, mreq commented on test/dummy/app/components/dummy/molecule/cards/medium_component.sass
> +    min-height: 200px
![image](https://github.com/sinfin/folio/assets/1286942/b394e187-befe-471d-af86-18bd0c23b588)

2024-01-09 10:28 UTC, mreq commented on test/dummy/app/components/dummy/molecule/cards/large_component.sass
> +    margin-top: $grid-gutter-base
ne, kdyz neni vyplneny titulek - pridal jsem ti do showcase

2024-01-09 10:35 UTC, mreq commented on test/dummy/app/components/dummy/molecule/cards/large_component.sass
> +    transform: scale(1.05)
obrazek se hyba i kdyz karta neni klikatelna

2024-01-10 05:48 UTC, merged