Martin/181/tabs
sinfin/folio pull request #192
Opened 2024-01-05 12:16 UTC by MartinLipan

2024-01-05 13:30 UTC, mreq requested changes
Prosim doplnit dolni border. Nepouzivat `$dark`, ale barvy z kitu.

2024-01-08 11:49 UTC, MartinLipan commented
> $dark

můžeš to pls upřesnit, resp. ideálně poslat odkaz, kde to najdu ve figmě?

2024-01-09 09:13 UTC, mreq commented
@MartinLipan V navrhu je dole linka.

https://www.figma.com/file/lR9K0yYlfS0zic4ygo8aF6/Folio---Design-System?node-id=3102%3A5447&mode=dev

![image](https://github.com/sinfin/folio/assets/1286942/7d3fe1d2-2375-43c6-990e-5bff3bad5960)

2024-01-09 09:58 UTC, MartinLipan commented
> @MartinLipan V navrhu je dole linka.

@mreq upraveno

2024-01-09 10:52 UTC, mreq commented
Diky. Jeste domluvte s @densimn, jak na mobilu. Zejmena, kdyz bude tabu vic.

![image](https://github.com/sinfin/folio/assets/1286942/b5758d2f-18e9-4961-9d7b-3daf7e3519bc)

2024-01-09 13:26 UTC, MartinLipan commented
> Diky. Jeste domluvte s @densimn, jak na mobilu. Zejmena, kdyz bude tabu vic.

@mreq taby upraveny podle domluvy

2024-01-09 13:50 UTC, mreq commented
@MartinLipan nezapomnel jsi pushnout?

2024-01-09 13:53 UTC, MartinLipan commented
@mreq přesně tak, už je to tam :)

2024-01-09 13:56 UTC, merged