turnstile validation on sign_up/sign_in
sinfin/folio pull request #336
Opened 2024-11-15 11:48 UTC by cabaktom

Přidáno před `invitation#create` a `session#create`

- Nevím, kam bych měl dát `//= require folio/cloudflare_turnstile`, nenašel jsem žádný `base.js` file. Teď je to v `devise.js`, ale Turnstile bude použit i mimo Devise
- Při `appearance: "interaction-only"` na turnstile widgetu (ukáže se jen tehdy, když vyžaduje akci od uživatele) zůstává ve formuláři prázdné místo:

![image](https://github.com/user-attachments/assets/4a6e9fed-00e3-4b70-b313-403dee645777)

Možná by šlo vyřešit schováním widgetu do chvíle, kdy ta interakce je vyžadována? Ale netuším, jak to zjistit. Stejný problém je v jiném projektu, kde je to uděláno podobně, jen tam není takovýto submit button pod inputy a to prázdné místo vidět není.

Klíče, se kterými jsem testoval:
```
# CLOUDFLARE_TURNSTILE_SITE_KEY=1x00000000000000000000AA # always passes, visible
# CLOUDFLARE_TURNSTILE_SITE_KEY=2x00000000000000000000AB # always blocks, visible
# CLOUDFLARE_TURNSTILE_SITE_KEY=1x00000000000000000000BB # always passes, invisible
# CLOUDFLARE_TURNSTILE_SITE_KEY=2x00000000000000000000BB # always blocks, invisible
CLOUDFLARE_TURNSTILE_SITE_KEY=3x00000000000000000000FF # forces an interactive challenge, visible
CLOUDFLARE_TURNSTILE_SECRET_KEY=1x0000000000000000000000000000000AA # always passes 
# CLOUDFLARE_TURNSTILE_SECRET_KEY=2x0000000000000000000000000000000AA # always fails 
# CLOUDFLARE_TURNSTILE_SECRET_KEY=3x0000000000000000000000000000000AA # yields a "token already spent" error
```

2024-11-19 07:12 UTC, mreq requested changes

2024-11-19 07:12 UTC, mreq commented on app/assets/javascripts/folio/cloudflare_turnstile.js
> +}
Nelibi se mi, ze je to rozstrakane na spouste mist. Udelejme prosim `Folio::Security::TurnstileComponent`, kde se tahle logika seskupi. V `render?` bude mit tu `Folio::Security.captcha_provider == :turnstile`, javascript bude pres stimulus. Kdyztak se porad s @davidduben nebo @VladaTrefil

2024-11-19 07:12 UTC, mreq commented on app/controllers/concerns/folio/has_turnstile_validation.rb
> +      redirect_path = defined?(turnstile_failure_redirect_path) ? turnstile_failure_redirect_path : root_path
pridejme tady `def turnstile_failure_redirect_path` namisto pouziti `defined?`

2024-11-19 08:16 UTC, mreq requested changes

2024-11-19 08:16 UTC, mreq commented on config/initializers/folio_security.rb
> +end
Myslim, ze cely tenhle modul je vlastne zbytecny. Jen shromazduje ENV, coz se muze dit v komponente. Odstranil bych.

2024-11-19 08:16 UTC, mreq commented on app/controllers/concerns/folio/has_turnstile_validation.rb
> +module Folio::HasTurnstileValidation
Mozna bych to vnoril do `Folio::Captcha::Turnstile`?

2024-11-21 05:47 UTC, mreq requested changes

2024-11-21 05:47 UTC, mreq commented on app/components/folio/captcha/turnstile_component.js
> +    document.addEventListener("turbolinks:before-render", this.removeTurnstile.bind(this))
Na tohle mame https://github.com/sinfin/folio/blob/master/app/assets/javascripts/folio/remote_scripts.js

2024-11-21 05:47 UTC, mreq commented on app/components/folio/captcha/turnstile_component.js
> +    document.addEventListener("turbolinks:before-render", this.removeTurnstile.bind(this))
```
window.Folio.RemoteScripts.run({
  key: 'turnstile',
  urls: ['https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit']
}, () => {
  this.renderTurnstile()
}, () => {
  console.error('error')
})
```

2024-11-21 05:47 UTC, mreq commented on app/components/folio/captcha/turnstile_component.js
> +    document.removeEventListener("turbolinks:before-render", this.removeTurnstile.bind(this))
tady jen `this.removeTurnstile()`

2024-11-21 05:47 UTC, mreq commented on app/components/folio/captcha/turnstile_component.js
> +    const turnstileContainer = document.querySelector(".cf-turnstile")
Tohle by za tebe mela prave resit komponent. Udelat to vzdy jen pro `this.element`.

2024-11-21 05:52 UTC, mreq commented
> Kam dát //= require folio/captcha/turnstile_component? Teď je to v devise.js a chtěl jsem podle toho vytvořit captcha.js, ale nevím jestli pak ten captcha file musím někde registrovat, protože takhle se mi controller nepřipojil.

Takhle je to ok.

> Přihlášení (session) při nevyplnění captcha udělá reload a ztratí se vyplněná políčka. S tím je spojené to, že když poprvé vyplním email i heslo, ale nedám captchu, dá mi to error, jenže pak stačí vyplnit jen email nebo heslo, zaškrtnout captchu a odeslat -> přihlásím se. Asi se nemažou data, jen se nezobrazují? viz video

To je zvlastni. A kdyz udelas `pry` v tom new formulari, tak `resource` ma oboji?

2024-11-21 09:48 UTC, cabaktom commented
> To je zvlastni. A kdyz udelas pry v tom new formulari, tak resource ma oboji?

@mreq není, i v params co dostane controller je jen ten email, pokud ho tam dám. Problém asi bude v `try_to_authenticate_resource`, kde se provede `self.resource = warden.authenticate!(auth_options)`. Jdu to zkoumat

2024-11-21 10:28 UTC, cabaktom commented
@mreq problém je jen v případě superadmina. Pokud chci vyvolat stejný problém s normálním uživatelem, který je jen na jedné site, nejde to. Když to udělám se superadminem, `current_user` se nastaví ještě než se vůbec začne provádět `sessions_controler#create` a i turnstile validace. 

Hádám, že to pochází z `Folio::Devise::CrossdomainController`, ale moc tomu nerozumím.

Asi bych to řešil přidáním `sign_out(:user) if current_user` do `submissions_controller#new`

2024-11-21 10:41 UTC, mreq commented
> problém je jen v případě superadmina

Pak bych to asi neresil. S tim auth_user by mel vedet @foton

2024-11-21 12:29 UTC, mreq requested changes

2024-11-21 12:29 UTC, mreq commented on app/components/folio/captcha/turnstile_component.js
> +    document.addEventListener("turbolinks:before-render", this.removeTurnstile.bind(this))
Tohle to furt zustalo. Cely connect by mel s tema remote scripts byt jen `this.loadTurnstileScript()`

2024-11-25 07:49 UTC, cabaktom commented
Snaž už takhle ok

2024-11-25 08:31 UTC, merged