Vložení obrázku v atomu - lazyloading nenačítá obrázky
sinfin/folio pull request #347
Opened 2024-12-02 12:22 UTC by VladaTrefil

https://sinfin-digital.atlassian.net/browse/ECO-359

Nejsou to asi vsechny mista s lazyloadingem, ale nevim, ktere dalsi chces prehodit. Taky tam zbyl nejaky `checkLazyload` a `forceCheck`, ale nevim o co se jedna.

2024-12-02 12:48 UTC, mreq requested changes

2024-12-02 12:48 UTC, mreq commented on react/src/components/Picture/index.js
>  }
tady ale nikde nepredavas ten `loading` , takze tam nic lazy neni, ne? Tu `LazyLoad` komponentu by take melo jit smazat

2024-12-03 21:28 UTC, VladaTrefil commented on react/src/components/Picture/index.js
>  }
Opraveno.

2024-12-03 21:28 UTC, VladaTrefil commented on react/package.json
> -    "react-lazyload": "^2.3.0",
@mreq odebral jsem rovnou ten react-lazyload, protoze tam ted neni nijak pouzity.

2024-12-11 08:10 UTC, merged